spring:
  profiles:
    active: dev
---
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: AIGOU_SERVER_DEV
  profiles: dev
---
server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: AIGOU_SERVER_TEST
  profiles: test