spring:
  profiles:
    active: dev
---
server:
  port: 8003
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aigou
    username: root
    password: 123456
  application:
    name: AIGOU_PRODUCT
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
mybatis-plus:
  mapper-locations: classpath:cn/zhengyq/aigou/mapper/*Mapper.xml
  type-aliases-package: cn.zhengyq.aigou.domain
---
server:
  port: 8004
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aigou
    username: root
    password: 123456
  application:
    name: AIGOU_PRODUCT_TEST
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
mybatis-plus:
  mapper-locations: classpath:cn/zhengyq/aigou/mapper/*Mapper.xml
  type-aliases-package: cn.zhengyq.aigou.domain
