spring:
  profiles:
    active: dev
---
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aigou
    username: root
    password: 123456
  application:
    name: AIGOU_PRODUCT
  profiles: dev
mybatis-plus:
  mapper-locations: classpath:cn/zhengyq/aigou/mapper/*Mapper.xml
  type-aliases-package: cn.zhengyq.aigou.domain
server:
  port: 8002
---
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aigou
    username: root
    password: 123456
  application:
    name: AIGOU_PRODUCT_TEST
  profiles: test
mybatis-plus:
  mapper-locations: classpath:cn/zhengyq/aigou/mapper/*Mapper.xml
  type-aliases-package: cn.zhengyq.aigou.domain
server:
  port: 8002
